// Generated by CoffeeScript 1.8.0
(function() {
  window.onload = function() {
    $('#create-option').on('submit', function() {
      var val;
      console.log('submitted');
      val = $('#new-option-text').val();
      if (!val) {
        return false;
      }
      $('#ballot').append($('<div class="option"></div>').html(val));
      $(this).detach();
      $('#ballot').append($(this));
      $('#new-option-text').focus().val('');
      return false;
    });
    return $('#sidebar-toggle').click(function() {
      return console.log($('#sidebar').toggleClass('open'));
    });
  };

}).call(this);
