// Generated by CoffeeScript 1.8.0
(function() {
  var stripeResponseHandler, submitPayment, validateEmail;

  window.validationErrors = false;

  validateEmail = function(email) {
    var re;
    re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    return re.test(email);
  };

  stripeResponseHandler = function(status, response) {
    var token;
    if (response.error) {
      $('#card-number').parent().find('.error').html(response.error.message);
      return $('#submit').prop('disabled', false);
    } else {
      token = response.id;
      return submitPayment(token);
    }
  };

  submitPayment = function(token) {
    var fname, i, lname, ticketNames, _i, _ref;
    if (window.validationErrors) {
      return;
    }
    ticketNames = [];
    for (i = _i = 1, _ref = parseInt($('#tickets').val()); 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      fname = $('#ticket-first-name-' + i).val();
      lname = $('#ticket-last-name-' + i).val();
      ticketNames.push({
        'first_name': fname,
        'last_name': lname
      });
    }
    console.log(ticketNames);
    return $.post('/pay', {
      names: JSON.stringify(ticketNames),
      email: $('#email').val(),
      tickets: $('#tickets').val(),
      token: token
    }, function() {
      console.log("PAYMENT SUCCESSFUL!");
      $('#myModal').modal('hide');
      return $('#buy-tickets').html('Purchase Successful!').prop('disabled', true).append("<h6 class=\"small\">An email has been sent</h6>");
    });
  };

  window.onload = function() {
    Stripe.setPublishableKey('pk_live_DU7Bp9hKLze0s8vO8ejP9NqY');
    $('#tickets').on('change', function() {
      var $ticket_name_template, i, price, tickets, _i, _ref, _results;
      tickets = $(this).val();
      price = parseFloat($('#calc-price').html());
      $('#calc-tickets').html(tickets);
      $('#calc-total').html((parseInt(tickets) * price).toFixed(2));
      $ticket_name_template = $($('#ticket-group').children()[0]);
      $('.ticket-name').remove();
      _results = [];
      for (i = _i = 1, _ref = parseInt(tickets); 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        $ticket_name_template = $ticket_name_template.clone();
        $ticket_name_template.find('label').each(function() {
          var for_attr;
          for_attr = $(this).attr('for');
          return $(this).attr('for', for_attr.substring(0, for_attr.length - 1) + i);
        });
        $ticket_name_template.find('input').each(function() {
          var input_id, input_name;
          input_name = $(this).attr('name');
          $(this).attr('name', input_name.substring(0, input_name.length - 1) + i);
          input_id = $(this).attr('id');
          return $(this).attr('id', input_id.substring(0, input_id.length - 1) + i);
        });
        _results.push($('#ticket-group').append($ticket_name_template));
      }
      return _results;
    });
    return $('form').on('submit', function(e) {
      var card_cvc, card_month, card_number, card_year, email, first_name, last_name, tickets;
      e.preventDefault();
      $('#submit').prop('disabled', true);
      first_name = $('#first-name').val();
      last_name = $('#last-name').val();
      email = $('#email').val();
      card_number = $('#card-number').val();
      card_cvc = $('#card-cvc').val();
      card_month = $('#card-month').val();
      card_year = $('#card-year').val();
      tickets = $('#tickets').val();
      window.validationErrors = false;
      $('.error').each(function() {
        return $(this).text('');
      });
      if (!validateEmail(email)) {
        $('#email').parent().find('.error').text('This email looks invalid.');
        $('#submit').prop('disabled', false);
        window.validationErrors = true;
      }
      return Stripe.card.createToken($('form'), stripeResponseHandler);
    });
  };

}).call(this);
