// Generated by CoffeeScript 1.8.0
(function() {
  var initHome, initVoty, newVoty, switchView;

  switchView = function(id) {
    console.log('switchView', id);
    return $('.view').velocity({
      opacity: 0
    }, {
      complete: function() {
        console.log('switchView complete');
        $('.view').addClass('hidden');
        $('#' + id).removeClass('hidden');
        return $('#' + id).velocity({
          opacity: 1
        });
      }
    });
  };

  newVoty = function() {
    var success;
    return $.post('/new', success = function(data, textStatus, jqXHR) {
      window.Noty = JSON.parse(data);
      switchView('voty');
      return initVoty();
    });
  };

  initVoty = function() {
    $('#create-option').on('submit', function() {
      var newOption, slabEl, val;
      console.log('submitted');
      val = $('#new-option-text').val();
      if (!val) {
        return false;
      }
      slabEl = $('<span style="width: 100%; margin: 5px;"></span>').html(val);
      newOption = $('<div class="option"></div>').append(slabEl);
      $('#ballot').append(newOption);
      slabEl.slabText();
      $(this).detach();
      $('#ballot').append($(this));
      $('#new-option-text').focus().val('');
      return false;
    });
    return $('#sidebar-toggle').click(function() {
      $('#sidebar').toggleClass('open');
      return $(this).toggleClass('open');
    });
  };

  initHome = function() {
    return $('#new-voty').click(function() {
      newVoty();
      return false;
    });
  };

  window.onload = function() {
    initHome();
    return initVoty();
  };

}).call(this);
